spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/playmats-ec
    # username: postgres
    username: admin
    password: kami123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

