spring:
  application:
    name: app
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  datasource:
    url: jdbc:postgresql://localhost:5432/playmats-ec
    username: postgres
    # username: admin
    password: kami123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cloudinary:
  cloud-name: ${CLOUD_NAME:''}
  api-key: ${CLOUD_API_KEY:''}
  api-secret: ${CLOUD_API_SECRET:''}